// CODIGOS DE LA TABLA PARAMETRO
export const ENVIO_CORREO_NIVEL = "ENVIO_CORREO_NIVEL";
export const LISTA_TIPO_2 = "LISTA_TIPO_2";

// TIPOS DE RIESGOS
export const RIESGO_NO_HAY = 0;
export const RIESGO_BAJO = 1;
export const RIESGO_MEDIO = 2;
export const RIESGO_ALTO = 3;

// NOMBRE DE LAS PLANTILLAS DE NOTIFICACIONES DE CORREO
export const TEMPLATE_NOTIFICACION_CORREO = "template-listacontrol";
